<template>
<lay-layout>
  <lay-header>
    <lay-logo></lay-logo>
  </lay-header>
  <lay-side></lay-side>
  <lay-body>
    <router-view></router-view>
  </lay-body>
  <lay-footer></lay-footer>
</lay-layout>
</template>